<div class="ynwtlist">
						<div class="slt">
							<a href="[field:arcurl/]"> <img src="[field:picname/]" alt=""> </a>
						</div>
						<div class="newslis newslisyn">
							<div class="newslistop">
								<section class="font4">
									<a target="_blank" href="[field:arcurl/]">[field:title/]</a>
								</section>
								<section>[field:pubdate function="MyDate('Y-m-d',@me)"/]</section>
							</div>
							<div style="clear:both"></div>
							<p class="color1"> [field:description/] </p>
						</div>
					</div>