<div class="newsbottomlist">
                        <div>
                            <section class="font3">[field:pubdate function="MyDate('d',@me)"/]</section>
                            <section class="color1">[field:pubdate function="MyDate('Y-m-d',@me)"/]</section>
                        </div>
                        <div>
                            <section class="newsbotttile"> <section><a target="_blank" href="[field:arcurl/]">[field:title/]</a></section></section>
                            <section class="color1">
                                 [field:description/]
                            </section>
                        </div>
                        <div style="clear:both"></div>
                    </div>