<?php
$z[0]=Array("global","",59,91);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",144,172);
$z[1][4]['name']="cfg_addressyi";
$z[2]=Array("global","",240,272);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",317,338);
$z[3][4]['name']="cfg_QQ";
$z[4]=Array("global","",386,418);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",469,490);
$z[5][4]['name']="cfg_wx";

?>