<?php
$z[0]=Array("global","",62,94);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",148,176);
$z[1][4]['name']="cfg_addressyi";
$z[2]=Array("global","",248,280);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",326,347);
$z[3][4]['name']="cfg_QQ";
$z[4]=Array("global","",399,431);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",483,504);
$z[5][4]['name']="cfg_wx";

?>