<?php
$z[0]=Array("global","",99,131);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",213,237);
$z[1][4]['name']="cfg_phone";
$z[2]=Array("channelartlist","\n			<li>\n				<a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\n				<div class=\"arrow-up\"></div>\n				<div class=\"us\">\n					{dede:channel type='son' noself='yes' }\n					<div>\n						<a href=\"[field:typelink/]\">[field:typename/]</a>\n					</div>\n					{/dede:channel}\n				</div>\n			</li>\n			",351,806);
$z[2][4]['typeid']="1,4,7";
$z[2][4]['currentstyle']="<li class='active'> <a href='~typelink~'>~typename~</a> </li>";
$z[3]=Array("type","\n			<li>\n				<a href=\"[field:typelink/]\">[field:typename/]</a>\n			</li>\n			",836,945);
$z[3][4]['typeid']="1";
$z[4]=Array("type","\n			<li>\n				<a href=\"[field:typelink/]\">[field:typename/]</a>\n			</li>\n			",972,1081);
$z[4][4]['typeid']="6";
$z[5]=Array("type","\n			<li>\n				<a href=\"[field:typelink/]\">[field:typename/]</a>\n			</li>\n			",1108,1217);
$z[5][4]['typeid']="7";
$z[6]=Array("type","\n			<li>\n				<a href=\"[field:typelink/]\">[field:typename/]</a>\n			</li>\n			",1244,1354);
$z[6][4]['typeid']="23";
$z[7]=Array("type","\n			<li>\n				<a href=\"[field:typelink/]\">[field:typename/]</a>\n			</li>\n			",1381,1491);
$z[7][4]['typeid']="16";
$z[8]=Array("type","\n			<li>\n				<a href=\"[field:typelink/]\">[field:typename/]</a>\n			</li>\n			",1500,1610);
$z[8][4]['typeid']="18";
$z[9]=Array("type","\n			<li>\n				<a href=\"[field:typelink/]\">[field:typename/]</a>\n			</li>\n			",1615,1725);
$z[9][4]['typeid']="19";
$z[10]=Array("type","\n			<li>\n				<a href=\"[field:typelink/]\">[field:typename/]</a>\n			</li>\n			",1726,1836);
$z[10][4]['typeid']="21";
$z[11]=Array("type","\n			<li>\n				<a href=\"[field:typelink/]\">[field:typename/]</a>\n			</li>\n			",1836,1945);
$z[11][4]['typeid']="6";

?>