<?php
$z[0]=Array("global","",122,154);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",244,268);
$z[1][4]['name']="cfg_phone";
$z[2]=Array("channelartlist","\r\n      <li>\r\n        <a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n        <!--<a href=\"/a/customerservice/1/\">软件下载</a>-->\r\n        <div class=\"arrow-up\"></div>\r\n        <div class=\"us\">\r\n          {dede:channel type='son' noself='yes' }\r\n          <div><a href=\"[field:typelink/]\">[field:typename/]</a></div>\r\n          {/dede:channel}\r\n        </div>\r\n      </li>\r\n      ",387,936);
$z[2][4]['typeid']="1,7,16";
$z[2][4]['currentstyle']="<li class='active'><a href='~typelink~'>~typename~</a> </li>";
$z[3]=Array("type","\r\n      <li>\r\n        <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n      </li>\r\n      ",946,1072);
$z[3][4]['typeid']="6";
$z[4]=Array("type","\r\n      <li>\r\n        <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n      </li>\r\n      ",1080,1207);
$z[4][4]['typeid']="18";
$z[5]=Array("type","\r\n      <li>\r\n        <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n      </li>\r\n      ",1216,1343);
$z[5][4]['typeid']="19";
$z[6]=Array("type","\r\n      <li>\r\n        <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n      </li>\r\n      ",1348,1475);
$z[6][4]['typeid']="21";

?>