<?php
$z[0]=Array("global","",232,264);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",314,346);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",396,428);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",477,509);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",542,574);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("field","",619,638);
$z[5][4]['name']="title";
$z[6]=Array("include","",728,763);
$z[6][4]['filename']="head.htm";
$z[7]=Array("type","\n					<img src=\"/templets/lanrui/images/banner[field:id/].jpg\" style=\"padding-bottom:10px;\" alt=\"[field:typename/]\" /> ",830,972);
$z[8]=Array("field","",1016,1037);
$z[8][4]['name']="content";
$z[9]=Array("include","",1038,1075);
$z[9][4]['filename']="footer.htm";
$z[10]=Array("global","",1101,1133);
$z[10][4]['name']="cfg_templets_skin";

?>