<?php
$z[0]=Array("global","",246,278);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",331,363);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",416,448);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",500,532);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",569,601);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("field","",649,668);
$z[5][4]['name']="title";
$z[6]=Array("include","",770,805);
$z[6][4]['filename']="head.htm";
$z[7]=Array("type","\r\n                <img src=\"/templets/lanrui/images/banner[field:id/].jpg\" style=\"padding-bottom:10px;\" alt=\"[field:typename/]\" />                ",905,1074);
$z[8]=Array("field","",1145,1166);
$z[8][4]['name']="content";
$z[9]=Array("include","",1177,1214);
$z[9][4]['filename']="footer.htm";
$z[10]=Array("global","",1246,1278);
$z[10][4]['name']="cfg_templets_skin";

?>