<?php
$z[0]=Array("global","",232,264);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",314,346);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",396,428);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",477,509);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("field","",540,559);
$z[4][4]['name']="title";
$z[5]=Array("include","",647,682);
$z[5][4]['filename']="head.htm";
$z[6]=Array("type"," <img src=\"/templets/lanrui/images/banner[field:id/].jpg\" style=\"padding-bottom:10px;\" alt=\"[field:typename/]\" /> ",744,881);
$z[7]=Array("field","",915,936);
$z[7][4]['name']="content";
$z[8]=Array("global","",1076,1108);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("arclist","\n							<div class=\"newslis\">\n								<div class=\"newslistop\">\n									<section>\n										<a target=\"_blank\" href=\"[field:arcurl/]\">[field:title/]</a>\n									</section>\n									<section>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</section>\n								</div>\n								<div style=\"clear:both\"></div>\n								<p> [field:description/] </p>\n							</div> ",1211,1655);
$z[9][4]['pagesize']="2";
$z[9][4]['typeid']="18";
$z[9][4]['orderby']="pubdate";
$z[9][4]['titlelen']="30";
$z[10]=Array("arclist","\n						<div class=\"newsbottomlist\">\n							<div>\n								<section class=\"font3\">[field:pubdate function=\"MyDate('d',@me)\"/]</section>\n								<section class=\"color1\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</section>\n							</div>\n							<div>\n								<section class=\"newsbotttile\">\n									<section>\n										<a target=\"_blank\" href=\"[field:arcurl/]\">[field:title/]</a>\n									</section>\n								</section>\n								<section class=\"color1\"> [field:description/] </section>\n							</div>\n							<div style=\"clear:both\"></div>\n						</div> ",1741,2379);
$z[10][4]['pagesize']="5";
$z[10][4]['typeid']="6";
$z[10][4]['orderby']="pubdate";
$z[10][4]['titlelen']="30";
$z[11]=Array("include","",2408,2445);
$z[11][4]['filename']="footer.htm";
$z[12]=Array("global","",2469,2501);
$z[12][4]['name']="cfg_templets_skin";
$z[13]=Array("global","",2548,2580);
$z[13][4]['name']="cfg_templets_skin";

?>