<?php
$z[0]=Array("global","",225,257);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",306,338);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",387,419);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",467,499);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("field","",529,548);
$z[4][4]['name']="title";
$z[5]=Array("include","",630,665);
$z[5][4]['filename']="head.htm";
$z[6]=Array("type","					<img src=\"/templets/lanrui/images/banner[field:id/].jpg\" style=\"padding-bottom:10px;\" alt=\"[field:typename/]\" /> ",727,868);
$z[7]=Array("field","",902,923);
$z[7][4]['name']="content";
$z[8]=Array("global","",1064,1096);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("arclist","							<div class=\"newslis\">								<div class=\"newslistop\">									<section>										<a target=\"_blank\" href=\"[field:arcurl/]\">[field:title/]</a>									</section>									<section>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</section>								</div>								<div style=\"clear:both\"></div>								<p>									[field:description/]								</p>							</div>							",1209,1664);
$z[9][4]['pagesize']="3";
$z[9][4]['typeid']="18";
$z[9][4]['orderby']="pubdate";
$z[9][4]['titlelen']="30";
$z[10]=Array("arclist","						<div class=\"newsbottomlist\">							<div>								<section class=\"font3\">[field:pubdate function=\"MyDate('d',@me)\"/]</section>								<section class=\"color1\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</section>							</div>							<div>								<section class=\"newsbotttile\">									<section>										<a target=\"_blank\" href=\"[field:arcurl/]\">[field:title/]</a>									</section>								</section>								<section class=\"color1\">									[field:description/]								</section>							</div>							<div style=\"clear:both\"></div>						</div>						",1757,2400);
$z[10][4]['pagesize']="5";
$z[10][4]['typeid']="6";
$z[10][4]['orderby']="pubdate";
$z[10][4]['titlelen']="30";
$z[11]=Array("include","",2433,2470);
$z[11][4]['filename']="footer.htm";
$z[12]=Array("global","",2494,2526);
$z[12][4]['name']="cfg_templets_skin";
$z[13]=Array("global","",2572,2604);
$z[13][4]['name']="cfg_templets_skin";

?>